- name: Install openssh server
  package: name=openssh-server state=present

- name: check if we have a ed25519 cert to copy
  local_action: stat path="{{ fetch_dir }}/{{ ansible_hostname }}_ssh_host_ed25519_key-cert.pub"
  register: host_key_cert
  become: false

- name: copy ssh host key cert
  copy:
    src="{{ fetch_dir }}/{{ ansible_hostname }}_ssh_host_ed25519_key-cert.pub"
    dest=/etc/ssh/ssh_host_ed25519_key-cert.pub
  when: host_key_cert.stat.exists
  notify: restart sshd

- set_fact: ssh_ed25519_cert_bool={{ host_key_cert.stat.exists }}
  tags: bugga

- name: Configure ssh client defaults
  copy:
    src=ssh_config
    dest=/etc/ssh/ssh_config
    owner=root
    group=root
    mode=0444

- name: Provide safe-size DH params
  copy:
    src=moduli
    dest=/etc/ssh/moduli
    owner=root
    group=root
    mode=0444

- name: Configure global ssh known_hosts
  template:
    src=ssh_known_hosts.j2
    dest=/etc/ssh/ssh_known_hosts
    owner=root
    group=root
    mode=0444

- name: Create sshd access groups
  group:
    name={{ item }}
    state=present
    system=yes
  with_items:
    - sshusers

- name: Explicitly allow ansible ssh user
  user:
    name={{ ansible_user }}
    groups=sshusers
    append=yes

- name: Configure ssh daemon
  template:
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root
    group=root
    mode=0444
  notify: restart sshd
