---

- name: Create ceph system user
  user:
    name=ceph
    state=present
    home=/var/lib/ceph
    shell=/bin/bash
    createhome=yes
  when: "'ceph-cluster' in group_names"

- name: Securing ceph home directory
  file:
    path=/var/lib/ceph
    state=directory
    group=ceph
    owner=ceph
    mode=0750
  when: "'ceph-cluster' in group_names"

- name: Create /var/lib/ceph/.ssh
  file:
    path=/var/lib/ceph/.ssh
    state=directory
    owner=ceph
    group=ceph
    mode=0750
  when: "'ceph-cluster' in group_names"

- name: copying ceph authorized key
  authorized_key:
    user=ceph
    key="{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  when: "'ceph-cluster' in group_names"

- name: Adding ceph sudo rule
  template:
    src=ceph_sudo_rule.j2
    dest=/etc/sudoers.d/ceph
    owner=root
    group=root
  when: "'ceph-cluster' in group_names"

- name: Explicitly allow ceph ssh user
  user:
    name=ceph
    groups=sshusers
    append=yes
  when: "'ceph-cluster' in group_names"

- name: creating /etc/hosts
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0444
  tags: ceph_install
    
- name: making sure /etc/ceph exists
  file:
    path=/etc/ceph
    state=directory
    owner=root
    group=adm
    mode=0550
  when: "'ceph-cluster' in group_names"
  tags: ceph_install

- name: checking if ceph is in modules-load.d
  template:
    src=kernelmodule_ceph.conf.j2
    dest=/etc/modules-load.d/ceph.conf
    owner=root
    group=root
    mode=0444
  notify: load ceph kernel module
  when: "'ceph-cluster' in group_names"
  tags: ceph_install

- name: check is ceph-mon.service exists
  stat:
    path=/lib/systemd/system/ceph-mon.service
  register: ceph_mon

- name: Enable the ceph-mon.service
  service:
    name=ceph-mon.service
    enabled=yes
  when: ceph_mon.stat.exists and 'ceph-mons' in group_names

- name: copy local repository signing key
  copy:
    src=rre.gpg
    dest=/etc/apt/trusted.gpg.d/rre.gpg
    owner=root
    group=root
    mode=0600
  notify: apt-update
  when: "'raspberry-pi' in group_names"

- name: adding local repository
  copy:
    src=rre.list
    dest=/etc/apt/sources.list.d/rre.list
    owner=root
    group=root
    mode=0644
  notify: apt-update
  when: "'raspberry-pi' in group_names"

- name: Set raspberry pi local repository
  copy:
    src=raspberrypi.pref
    dest=/etc/apt/preferences.d/raspberrypi.pref
    owner=root
    group=root
    mode=0644
  notify: apt-update
  when: "'raspberry-pi' in group_names"

